<?xml version="1.0"?>
<robot name="atrias_robot"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
			 xmlns:xacro="http://www.ros.org/wiki/xacro"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
			 xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
			 xmlns:geo="http://willowgarage.com/xmlschema/#geo" 
			 xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom" 
			 xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body" >

	<property name="M_PI" value="3.14159"/>
	<property name="SQRT_2" value="1.41421356"/>

	<!--	<property name="initial_height" value="1." /> -->
	<property name="initial_height" value="0.9" />
	<property name="body_size" value="0.25 0.15 0.15" />

	<property name="visual_motor_length" value="0.4" />
	<property name="visual_motor_radius" value="0.015" />
	<!--	<property name="maximum_motor_torque" value="${130*20}" />-->
	<!--	<property name="maximum_motor_velocity" value="${26.17993878/20}" />-->
	<property name="maximum_motor_torque" value="10000000" />
	<property name="maximum_motor_velocity" value="10000000" />
	<property name="motor_damping_coefficient" value="0.2" />

	<property name="leg_segment_radius" value="0.02" />
	<property name="A_length" value="0.4" />
	<property name="B_length" value="0.5" />
	<property name="C_length" value="0.5" />
	<property name="D_length" value="0.5" />

	<property name="spring_stiffness" value="500" />
	<property name="motor_damping" value="0" />
	<property name="leg_seg_damping" value="0" />

	<xacro:macro name="atrias_robot">

		<!--#########################################################################-->
		<!--																	Body	 				 												-->
		<!--#########################################################################-->

		<link name="body_link">
			<inertial>
				<mass value="24" />  <!-- From RC scale -->
<!--				<mass value="10" />-->
				<origin xyz="0 0 0" />
				<inertia ixx="1.37" ixy="0" ixz="0"
				         iyy="1.37" iyz="0"
				         izz="1" />
			</inertial>   
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
				  <box size="${body_size}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
				  <box size="${body_size}" />
				</geometry>
			</collision>
		</link>
		<gazebo reference="body_link">
			<material>Gazebo/BumpyMetal</material>
		</gazebo>

		<gazebo>
			<controller:position_body name="position_body" plugin="libposition_body.so">
				<alwaysOn> true </alwaysOn>
				<updateRate> 10000 </updateRate>
				<bodyName> body_link </bodyName>
			</controller:position_body>
		</gazebo>

		<!--#########################################################################-->
		<!--																	Motor A				 												-->
		<!--#########################################################################-->


		<joint name="hip_motorA_joint" type="revolute">
			<axis xyz="0 1 0" />
			<anchor xyz="0 0 0" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<parent link="body_link" />
			<child link="motorA_link" />
			<limit lower="${-M_PI/4-0.3054}" upper="${-M_PI/4+2.3562}" effort="10000000000000" velocity="100000000000000" />
		</joint>


		<link name="motorA_link">
			<inertial>
				<mass value="0.01"/>
				<origin xyz="0 0 0" />
				<inertia ixx="10" ixy="0" ixz="0"
				         iyy="10" iyz="0"
				         izz="10" />
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 ${-M_PI/4} 0" />
				<geometry>
				  <cylinder length="${visual_motor_length}" radius="${visual_motor_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 ${-M_PI/4} 0" />
				<geometry>
				  <box size="0 0 0" />
				</geometry>
			</collision>
		</link>
		<gazebo reference="motorA_link">
			<material> Gazebo/Green </material>
		</gazebo>

		<gazebo>
			<controller:joint_impedance name="motor_frictionA" plugin="libjoint_impedance.so">
				<alwaysOn> true </alwaysOn>
				<updateRate> 10000 </updateRate>
				<bodyName1> body_link </bodyName1>
				<bodyName2> motorA_link </bodyName2>
				<rotationalDamping> ${motor_damping} </rotationalDamping>
			</controller:joint_impedance>
		</gazebo>

		<gazebo>
			<controller:spring name="springA" plugin="libspring.so">
				<alwaysOn> true </alwaysOn>
				<updateRate> 10000 </updateRate>
				<bodyName1> motorA_link </bodyName1>
				<bodyName2> legA_link </bodyName2>
				<rotationalStiffness> ${spring_stiffness} </rotationalStiffness>
			</controller:spring>
		</gazebo>

		<!--#########################################################################-->
		<!--																	Motor B				 												-->
		<!--#########################################################################-->


<!--		  <joint name="hip_motorB_joint" type="fixed">-->
		<joint name="hip_motorB_joint" type="revolute">
			<axis xyz="0 1 0" />
			<anchor xyz="0 0 0" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<parent link="body_link" />
			<child link="motorB_link"/>
			<limit lower="${-5*M_PI/4+2.8362}" upper="${-5*M_PI/4+5.4978}" effort="10000000000000" velocity="100000000000000" />
		</joint>


		<link name="motorB_link">
			<inertial>
				<mass value="0.01"/>
				<origin xyz="0 0 0" />
				<inertia ixx="10" ixy="0" ixz="0"
				         iyy="10" iyz="0"
				         izz="10" />
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 ${M_PI/4} 0" />
				<geometry>
				  <cylinder length="${visual_motor_length}" radius="${visual_motor_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 ${M_PI/4} 0" />
				<geometry>
				  <box size="0 0 0" />
				</geometry>
			</collision>
		</link>
		<gazebo reference="motorB_link">
			<material>Gazebo/Green</material>
		</gazebo>

		<gazebo>
			<controller:joint_impedance name="motor_frictionB" plugin="libjoint_impedance.so">
				<alwaysOn> true </alwaysOn>
				<updateRate> 10000 </updateRate>
				<bodyName1> body_link </bodyName1>
				<bodyName2> motorB_link </bodyName2>
				<rotationalDamping> ${motor_damping} </rotationalDamping>
			</controller:joint_impedance>
		</gazebo>

		<gazebo>
			<controller:spring name="springB" plugin="libspring.so">
				<alwaysOn> true </alwaysOn>
				<updateRate> 10000 </updateRate>
				<bodyName1> motorB_link </bodyName1>
				<bodyName2> legB_link </bodyName2>
				<rotationalStiffness> ${spring_stiffness} </rotationalStiffness>
			</controller:spring>
		</gazebo>


		<!--#########################################################################-->
		<!--																	 Leg A 				 												-->
		<!--#########################################################################-->


		<joint name="body_legA_joint" type="revolute">
			<axis xyz="0 1 0" />
			<anchor xyz="0 0 0" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<parent link="body_link" />
			<child link="legA_link"/>
			<limit lower="${-M_PI/4-0.6545}" upper="${-M_PI/4+2.7053}" effort="1000000000000" velocity="100000000000000" />
		</joint>


		<link name="legA_link">
			<inertial>
				<mass value="0.66149"/>
				<origin xyz="${A_length/SQRT_2/2} 0 ${-A_length/SQRT_2/2}" />
				<inertia ixx="0.01910" ixy="0" ixz="0"
				         iyy="0.01910" iyz="0"
				         izz="0.01910" />
			</inertial>
			<visual>
				<origin xyz="${A_length/SQRT_2/2} 0 ${-A_length/SQRT_2/2}" rpy="0 ${-M_PI/4} 0" />
				<geometry>
				  <cylinder length="${A_length}" radius="${leg_segment_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="${A_length/SQRT_2/2} 0 ${-A_length/SQRT_2/2}" rpy="0 ${-M_PI/4} 0" />
				<geometry>
					<cylinder length="${A_length}" radius="${leg_segment_radius}" />
				</geometry>
			</collision>
		</link>
		<gazebo reference="legA_link">
			<material>Gazebo/Red</material>
		</gazebo>

		<gazebo>
			<controller:joint_impedance name="leg_seg_frictionA" plugin="libjoint_impedance.so">
				<alwaysOn> true </alwaysOn>
				<updateRate> 10000 </updateRate>
				<bodyName1> body_link </bodyName1>
				<bodyName2> legA_link </bodyName2>
				<rotationalDamping> ${leg_seg_damping} </rotationalDamping>
			</controller:joint_impedance>
		</gazebo>


		<!--#########################################################################-->
		<!--																	 Leg B 				 					 							-->
		<!--#########################################################################-->


		<joint name="body_legB_joint" type="revolute">
			<axis xyz="0 -1 0" />
			<anchor xyz="0 0 0" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<parent link="body_link" />
			<child link="legB_link"/>
			<limit lower="${-5*M_PI/4+2.4871}" upper="${-5*M_PI/4+5.4978}" effort="100000000000" velocity="100000000000000" />
		</joint>


		<link name="legB_link">
			<inertial>
				<mass value="0.68292"/>
				<origin xyz="${-B_length/SQRT_2/2} 0 ${-B_length/SQRT_2/2}" />
				<inertia ixx="0.02116" ixy="0" ixz="0"
				         iyy="0.02116" iyz="0"
				         izz="0.02116" />
			</inertial>
			<visual>
				<origin xyz="${-B_length/SQRT_2/2} 0 ${-B_length/SQRT_2/2}" rpy="0 ${M_PI/4} 0" />
				<geometry>
				  <cylinder length="${B_length}" radius="${leg_segment_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="${-B_length/SQRT_2/2} 0 ${-B_length/SQRT_2/2}" rpy="0 ${M_PI/4} 0" />
				<geometry>
					<cylinder length="${B_length}" radius="${leg_segment_radius}" />
				</geometry>
			</collision>
		</link>
		<gazebo reference="legB_link">
			<material>Gazebo/Red</material>
		</gazebo>

		<gazebo>
			<controller:joint_impedance name="leg_seg_frictionB" plugin="libjoint_impedance.so">
				<alwaysOn> true </alwaysOn>
				<updateRate> 10000 </updateRate>
				<bodyName1> body_link </bodyName1>
				<bodyName2> legB_link </bodyName2>
				<rotationalDamping> ${leg_seg_damping} </rotationalDamping>
			</controller:joint_impedance>
		</gazebo>

		<!--#########################################################################-->
		<!--																	 Leg C 				 									 			-->
		<!--#########################################################################-->

		<joint name="legA_legC_joint" type="revolute">
			<axis xyz="0 1 0" />
			<anchor xyz="${A_length/SQRT_2} 0 ${-A_length/SQRT_2}" />
			<origin xyz="${A_length/SQRT_2} 0 ${-A_length/SQRT_2}" rpy="0 0 0" />
			<parent link="legA_link" />
			<child link="legC_link"/>
			<limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="10000000000000" velocity="100000000000000" />
		</joint>


		<link name="legC_link">
			<inertial>
				<mass value="0.19126"/>
				<origin xyz="${-C_length/SQRT_2/2} 0 ${-C_length/SQRT_2/2}" />
				<inertia ixx="0.00633" ixy="0" ixz="0"
				         iyy="0.00633" iyz="0"
				         izz="0.00633" />
			</inertial>
			<visual>
				<origin xyz="${-C_length/SQRT_2/2} 0 ${-C_length/SQRT_2/2}" rpy="0 ${M_PI/4} 0" />
				<geometry>
				  <cylinder length="${C_length}" radius="${leg_segment_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="${-C_length/SQRT_2/2} 0 ${-C_length/SQRT_2/2}" rpy="0 ${M_PI/4} 0" />
				<geometry>
					<cylinder length="${C_length}" radius="${leg_segment_radius}" />
				</geometry>
			</collision>
		</link>
		<gazebo reference="legC_link">
			<material>Gazebo/Red</material>
		</gazebo>


		<!--#########################################################################-->
		<!--																	 Leg D 				 					 							-->
		<!--#########################################################################-->


		<joint name="legB_legD_joint" type="revolute">
			<axis xyz="0 1 0" />
			<anchor xyz="${-B_length/SQRT_2} 0 ${-B_length/SQRT_2}" />
			<origin xyz="${-B_length/SQRT_2} 0 ${-B_length/SQRT_2}" rpy="0 0 0" />
			<parent link="legB_link" />
			<child link="legD_link"/>
			<limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="10000000000000" velocity="100000000000000" />
		</joint>


		<link name="legD_link">
			<inertial>
				<mass value="0.42493"/>
				<origin xyz="${D_length/SQRT_2/2} 0 ${-D_length/SQRT_2/2}" />
				<inertia ixx="0.01243" ixy="0" ixz="0"
				         iyy="0.01243" iyz="0"
				         izz="0.01243" />
			</inertial>
			<visual>
				<origin xyz="${D_length/SQRT_2/2} 0 ${-D_length/SQRT_2/2}" rpy="0 ${-M_PI/4} 0" />
				<geometry>
				  <cylinder length="${D_length}" radius="${leg_segment_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="${D_length/SQRT_2/2} 0 ${-D_length/SQRT_2/2}" rpy="0 ${-M_PI/4} 0" />
				<geometry>
					<cylinder length="${D_length}" radius="${leg_segment_radius}" />
				</geometry>
			</collision>
		</link>
		<gazebo reference="legD_link">
			<material>Gazebo/Red</material>
		</gazebo>


		<gazebo>
			<joint:hinge name="legC_legD_joint">
				<body1>legC_link</body1>
				<body2>legD_link</body2>
				<anchor>legC_link</anchor>
				<axis>0 1 0</axis>
				<anchorOffset>${-C_length/SQRT_2} 0 ${-C_length/SQRT_2}</anchorOffset>
			</joint:hinge>
		</gazebo>


	</xacro:macro>


</robot>

