<?xml version="1.0"?>

<!-- ATRIAS 2.0 Hip Model -->
<!-- Adapted for ATRIAS 2.0 in Winter Term 2012 by Andrew Peekema and Matthew Rueben -->

<robot
	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
	xmlns:xacro="http://www.ros.org/wiki/xacro"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
	xmlns:geo="http://willowgarage.com/xmlschema/#geo" 
	xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom" 
	xmlns:torso="http://playerstage.sourceforge.net/gazebo/xmlschema/#torso" >

	<!-- Mathematical Constants -->
	<property name="M_PI" value="3.14159"/>
	<property name="SQRT_2" value="1.41421356"/>

	<!-- Visual Parameters (no effect on physical simulation) -->
    <property name="torso_size" value="0.25 0.2 0.18" />
	<property name="torsoMotor_radius" value="0.015" />
	<property name="torsoMotor_length" value="0.2" />
	<property name="coupling_radius" value="0.015" />

	<!-- Link Lengths -->
	<property name="torso_height" value="0.36" />
	<property name="torsoAttachment_length" value="0.17" />

	<!-- Link Masses -->
	<property name="torso_mass" value="0.500" />
	<property name="torsoMotor_mass" value="1.00" />
	<property name="torsoAttachment_mass" value="0.500" />

	<!-- Spring/Damping Coefficients -->
	<property name="torsoMotor_damping" value="${2*0.5*34.64}" />	<!-- 2*Zeta*sqrt(K) (Guessed Zeta)-->
	<property name="torsoMotor_friction" value="1" />				<!-- Guess -->


    <xacro:macro name="atrias_torso" params="torso_link" >

        <!--#########################################################################-->
        <!--                                Torso                                     -->
        <!--#########################################################################-->

        <link name="${torso_link}">
            <inertial>
                <origin xyz="0 0 0" />
                <mass value="${torso_mass}" />
                <inertia ixx="0.01" ixy="0" ixz="0"
                         iyy="0.01" iyz="0"
                         izz="0.01" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                  <box size="${torso_size}" />
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                  <box size="${torso_size}" />
                </geometry>
            </collision>
        </link>
        <gazebo reference="${torso_link}">
            <material>Gazebo/BumpyMetal</material>
        </gazebo>

    </xacro:macro>


	<xacro:macro name="torso_motor" params="torso_link reflect suffix hip_link" >

		<!--#########################################################################-->
		<!--						Torso Motor		                              -->
		<!--#########################################################################-->
	
		<joint name="torso_torsoMotor${suffix}_joint" type="continuous">
			<axis xyz="0 1 0" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<parent link="${torso_link}" />
			<child link="torsoMotor${suffix}" />
			<dynamics damping="${torsoMotor_damping}" friction="${torsoMotor_friction}" />
		</joint>

		<link name="torsoMotor${suffix}">
			<inertial>
				<mass value="${torsoMotor_mass}"/>
				<origin xyz="${reflect*0.05} 0 0" />
				<inertia ixx="3" ixy="0.0" ixz="0.0"
						 iyy="5" iyz="0.0"
						 izz="3" />
			</inertial>
			<visual>
				<origin xyz="${torsoMotor_length/2*reflect} 0 0" rpy="0 ${M_PI/2} 0" />
				<geometry>
				  <cylinder length="${torsoMotor_length}" radius="${torsoMotor_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="${torsoMotor_length/2*reflect} 0 0" rpy="0 ${M_PI/2} 0" />
				<geometry>
					<cylinder length="${torsoMotor_length}" radius="${torsoMotor_radius}" />
				</geometry>
			</collision>
		</link>

		<gazebo reference="torsoMotor${suffix}">
			<material> Gazebo/Green </material>
		</gazebo>


		<!--#########################################################################-->
		<!--						Coupling		                              -->
		<!--#########################################################################-->

		<joint name="torsoMotor${suffix}_coupling${suffix}_joint" type="continuous">
			<axis xyz="0 1 0" />
			<origin xyz="${torsoAttachment_length*reflect} 0 0" rpy="0 0 0" />
			<parent link="torsoMotor${suffix}" />
			<child link="coupling${suffix}" />
		</joint>

		<link name="coupling${suffix}">
			<inertial>
				<mass value="0.01"/>
				<origin xyz="0 0 0" />
				<inertia ixx="0.001" ixy="0.0" ixz="0.0"
						 iyy="0.001" iyz="0.0"
						 izz="0.001" />
			</inertial>
			<visual>
				<origin xyz="0 0 ${-torso_height/2}" rpy="0 0 0" />
				<geometry>
				  <cylinder length="${torso_height}" radius="${coupling_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0 ${-torso_height/2}" rpy="0 0 0" />
				<geometry>
					<cylinder length="${torso_height}" radius="${coupling_radius}" />
				</geometry>
			</collision>
		</link>

		<gazebo reference="coupling${suffix}">
			<material> Gazebo/Green </material>
		</gazebo>


		<!--#########################################################################-->
		<!--					Torso Attachment                                    -->
		<!--#########################################################################-->

		<joint name="torso_torsoAttachment${suffix}_joint" type="continuous">
			<axis xyz="0 1 0" />
			<origin xyz="0 0 ${-torso_height}" rpy="0 0 0" />
			<parent link="${torso_link}" />
			<child link="torsoAttachment${suffix}"/>
		</joint>

		<link name="torsoAttachment${suffix}">
			<inertial>
				<mass value="${torsoAttachment_mass}"/>
				<origin xyz="${reflect*0.05} 0 0" />
				<inertia ixx="0.01" ixy="0.0" ixz="0.0"
						 iyy="0.01" iyz="0.0"
						 izz="0.01" />
			</inertial>
			<visual>
				<origin xyz="${torsoAttachment_length/2*reflect} 0 0" rpy="0 ${M_PI/2} 0" />
				<geometry>
				  <cylinder length="${torsoAttachment_length}" radius="${torsoMotor_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="${torsoAttachment_length/2*reflect} 0 0" rpy="0 ${M_PI/2} 0" />
				<geometry>
				  <cylinder length="${torsoAttachment_length}" radius="${torsoMotor_radius}" />
				</geometry>
			</collision>
		</link>

		<gazebo reference="torsoAttachment${suffix}">
			<material> Gazebo/Red </material>
		</gazebo>


		<!--#########################################################################-->
		<!--					Four Bar Joint                                    -->
		<!--#########################################################################-->

		<gazebo>
			<joint:hinge name="torsoFourBar${suffix}_joint">
				<body1>coupling${suffix}</body1>
				<body2>torsoAttachment${suffix}</body2>
				<anchor>coupling${suffix}</anchor>
				<axis>0 1 0</axis>
				<anchorOffset>0 0 ${-torso_height}</anchorOffset>
			</joint:hinge>
		</gazebo>

	</xacro:macro>


    <xacro:macro name="torso_leg_joint" params="suffix reflect hip_link" >

		<!--#########################################################################-->
		<!--					Leg Attachment                                    -->
		<!--#########################################################################-->

		<joint name="torsoAttachment${suffix}_leg_joint" type="fixed">
			<origin xyz="${torsoAttachment_length*reflect} 0 0" rpy="0 0 ${-M_PI/2}" />
			<parent link="torsoAttachment${suffix}" />
			<child link="${hip_link}${suffix}"/>
		</joint>


	</xacro:macro>


</robot>

