<?xml version="1.0"?>
<robot name="atrias_robot"
	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#slider"
	xmlns:xacro="http://www.ros.org/wiki/xacro"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
	xmlns:geo="http://willowgarage.com/xmlschema/#geo" 
	xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom" 
	xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body" >

	<!-- Constants -->
	<property name="M_PI" value="3.14159"/>
	<property name="SQRT_2" value="1.41421356"/>

	<!-- Physical Properties -->
	<property name="upright_length" value="1" />
	<property name="boom_length" value="1" />
	<property name="pendulum_length" value="0.9" />
	<property name="spring_stiffness" value="3.5" />
	<property name="leg_seg_damping" value="0" />
	
	<!-- Initial Condition -->
	<property name="initial_height" value="${upright_length/SQRT_2 + B_length/SQRT_2}" />

	<!-- Visual Properties -->
	<property name="body_size" value="0.25 0.15 0.15" />
	<property name="leg_segment_radius" value="0.02" />

	<xacro:macro name="atrias_robot">

		<link name="world" />


		<!--#########################################################################-->
		<!--				 Upright				-->
		<!--#########################################################################-->


		<joint name="world_upright_joint" type="fixed">
			<!-- anchor xyz="0 0 0" / -->
			<axis xyz="0 0 1" rpy="0 0 0" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<parent link="world" />
			<child link="upright_link"/>
		</joint>


		<link name="upright_link">
			<inertial>
				<mass value="0.66149"/>
				<origin xyz="0 0 ${upright_length/2}" rpy="0 0 0" />
				<inertia ixx="0.01910" ixy="0" ixz="0"
				         iyy="0.01910" iyz="0"
				         izz="0.01910" />
			</inertial>
			<visual>
				<origin xyz="0 0 ${upright_length/2}" rpy="0 0 0" />
				<geometry>
				  <cylinder length="${upright_length}" radius="${leg_segment_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0 ${upright_length/2}" rpy="0 0 0"  />
				<geometry>
					<cylinder length="${upright_length}" radius="${leg_segment_radius}" />
				</geometry>
			</collision>
		</link>
		<gazebo reference="upright_link">
			<material>Gazebo/Red</material>
		</gazebo>


		<!--#########################################################################-->
		<!--				 Boom					-->
		<!--#########################################################################-->


		<joint name="upright_boom_joint" type="fixed">
			<axis xyz="0 0 1" />
			<!-- anchor xyz="0 0 0" / -->
			<origin xyz="0 0 ${upright_length}" rpy="0 0 0" />
			<parent link="upright_link" />
			<child link="boom_link"/>
		</joint>


		<link name="boom_link">
			<inertial>
				<mass value="0.68292"/>
				<origin xyz="${boom_length/2} 0 0" rpy="0 0 0" />
				<inertia ixx="0.02116" ixy="0" ixz="0"
				         iyy="0.02116" iyz="0"
				         izz="0.02116" />
			</inertial>
			<visual>
				<origin xyz="${boom_length/2} 0 0" rpy="0 ${M_PI/2} 0" />
				<geometry>
				  <cylinder length="${boom_length}" radius="${leg_segment_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="${boom_length/2} 0 0" rpy="0 ${M_PI/2} 0" />
				<geometry>
					<cylinder length="${boom_length}" radius="${leg_segment_radius}" />
				</geometry>
			</collision>
		</link>

		<gazebo reference="boom_link">
			<material>Gazebo/Red</material>
			<static>true</static>
		</gazebo>


		<!--#########################################################################-->
		<!--				 Pendulum                                    -->
		<!--#########################################################################-->


		<joint name="pendulum_joint" type="continuous">
			<axis xyz="0 1 0" />
			<origin xyz="${boom_length} 0 0" rpy="0 ${M_PI/18/5} 0" />
			<parent link="boom_link" />
			<child link="pendulum_link"/>
		</joint>


		<link name="pendulum_link">
			<inertial>
				<mass value="1"/>
				<origin xyz="0 0 ${-pendulum_length/2}" rpy="0 0 0" />
				<inertia ixx="0.245" ixy="0" ixz="0"
				         iyy="0.245" iyz="0"
				         izz="0.245" />
			</inertial>
			<visual>
				<origin xyz="0 0 ${-pendulum_length/2}" rpy="0 0 0" />
				<geometry>
				  <cylinder length="${pendulum_length}" radius="${leg_segment_radius}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0 ${-pendulum_length/2}" rpy="0 0 0" />
				<geometry>
					<cylinder length="${pendulum_length}" radius="${leg_segment_radius}" />
				</geometry>
			</collision>
		</link>

		<gazebo reference="pendulum_link">
			<material>Gazebo/Red</material>
		</gazebo>

		<gazebo>
			<controller:joint_impedance name="pendulum_damping" plugin="libjoint_impedance.so">
				<alwaysOn> true </alwaysOn>
				<updateRate> 10000 </updateRate>
				<bodyName1> upright_link </bodyName1>
				<bodyName2> pendulum_link </bodyName2>
				<rotationalDamping> 0 </rotationalDamping>
				<rotationalFriction> 0.01 </rotationalFriction>
			</controller:joint_impedance>
		</gazebo>

		<gazebo>
			<controller:spring name="pendulum_spring" plugin="libspring.so">
				<alwaysOn> true </alwaysOn>
				<updateRate> 10000 </updateRate>
				<bodyName1> upright_link </bodyName1>
				<bodyName2> pendulum_link </bodyName2>
				<rotationalStiffness> ${spring_stiffness} </rotationalStiffness>
			</controller:spring>
		</gazebo>
		<gazebo>	
			<controller:gazebo_ros_p3d name="p3d_base_controller" plugin="libgazebo_ros_p3d.so">
						   <alwaysOn>true</alwaysOn>
						   <updateRate>100.0</updateRate>
						   <bodyName>pendulum_link</bodyName>
						   <topicName>pendulum_pose_ground_truth</topicName>
						   <gaussianNoise>0.01</gaussianNoise>
						   <frameName>map</frameName>
						   <xyzOffsets>25.7 25.7 0</xyzOffsets> <!-- initialize odometry for fake localization-->
						   <rpyOffsets>0 0 0</rpyOffsets>
						   <interface:position name="p3d_base_position"/>
			</controller:gazebo_ros_p3d>

		</gazebo>

	</xacro:macro>


</robot>

